# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd2f8febe38287df385a8520b5a0fb5e8213e036f4e7486cedec55ff4ae8f263fe9523e06dbb50e344be7a7dabe5c172ecea8da8c16af911666fbbf8b681b4ee

test:
  secret_key_base: daa32a4f7256c7b70a29861c3414c57605c2a5dfe3ea1e267a52a4c775a539cef1f9273f39d7cf5a25bd2ab2ed34a57ed2524249fb981c30cf953ffebbdb0851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
